# Generated by Django 4.1.12 on 2023-10-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trader_traderecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
