# Generated by Django 4.1.12 on 2023-10-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_trader_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='made_profit',
            field=models.BooleanField(default=True),
        ),
    ]
